####################################
### anshul333y's hyprland config ###
####################################

source = ~/.config/hypr/hyprcolors.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
