####################################
### anshul333y's hyprland config ###
####################################

source = ~/.config/hypr/custom/hyprcolors.conf


### ENVIRONMENT ###

source = ~/.config/hypr/custom/environment.conf


### LOOK AND FEEL ###

source = ~/.config/hypr/custom/look.conf


### INPUT ###

source = ~/.config/hypr/custom/input.conf


### KEYBINDINGS ###

source = ~/.config/hypr/custom/keybindings.conf


### WINDOWS AND WORKSPACES ###

source = ~/.config/hypr/custom/window.conf
